//Step 9 of the pipedream workflow
export default defineComponent({
  async run({ steps, $ }) {
    const videoId = steps.validate_input.$return_value.videoId;

    // Grab the whole object from transcript_auto
    //const ta = steps.transcript_auto.$return_value || {};
    const ta = steps.transcript_final.$return_value || {};

    // This is already the array of items from YT-API
    const data = ta.transcript || [];

    // Normalize to your schema
    const segments = data
      .map((item) => ({
        start: (item.startMs || 0) / 1000,
        duration: ((item.endMs || 0) - (item.startMs || 0)) / 1000,
        text: String(item.text || "").replace(/\s+/g, " ").trim(),
      }))
      .filter((s) => s.text);

    const fullText = segments.map((s) => s.text).join(" ").trim();

    // Language from transcript_auto
    const language = ta.selectedTrackTitle || "unknown";

    // Rough heuristic: mark auto-generated if the title says so
    const isAutoGenerated = language.toLowerCase().includes("auto-generated");

    $.export(
      "$summary",
      `Extracted ${segments.length} transcript segments for ${videoId}`
    );

    return {
      videoId,
      language,
      isAutoGenerated,
      segments,
      fullText,
      segmentCount: segments.length,
    };
  },
});
